version: "2.27.1"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    ports:
      - "4566:4566"
  postgres:
    image: fetchdocker/data-takehome-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Fetch
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
